name: CI Pipeline

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests with pytest
        run: |
          # The python -c "import patch_modules" line is removed.
          # The -p pytest_firestore_mock flag ensures our plugin's pytest_configure hook runs.
          python -m pytest -p pytest_firestore_mock --maxfail=1 --disable-warnings -q
      

#      - name: Run linter
#        run: |
#          pip install flake8
#          flake8 .
